# TLS Configuration - Modern security settings
tls:
  options:
    modern:
      minVersion: VersionTLS13
      sniStrict: true
      preferServerCipherSuites: true
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
